" Auto Download
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.config/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'connorholyday/vim-snazzy'

call plug#end()

" Files
set nobackup
set noswapfile
set noundofile
set viminfo+=n~/.local/state/viminfo

" Colorscheme
let g:SnazzyTransparent = 1
colorscheme snazzy

