" packages
let s:plugins = [
      \ 'https://github.com/tpope/vim-commentary.git',
      \ 'https://github.com/tpope/vim-fugitive.git',
      \ 'https://github.com/tpope/vim-sensible.git',
      \ 'https://github.com/tpope/vim-sleuth.git',
      \ 'https://github.com/tpope/vim-surround.git',
      \ ]

let s:root = split(&packpath, ',')[0] . '/pack/p/start'
call mkdir(s:root, 'p')

if executable('git')
  for s:url in s:plugins
    let s:name = fnamemodify(s:url, ':t:r')
    let s:dir  = s:root . '/' . s:name
    if !isdirectory(s:dir)
      call system('git clone --depth 1 ' . shellescape(s:url) . ' ' . shellescape(s:dir))
    endif
  endfor
endif

packloadall

" options
filetype plugin indent on
syntax on

set nobackup
set noswapfile
set noundofile
set viminfo+=n~/.local/state/viminfo

set clipboard=unnamed

set number

colorscheme ansi
